network_name = "playground"
project_id   = "sage-dragon-363717"
gke_name     = "playground-backend"
region       = "us-east1"
pg_location  = "us-east1-b"
state_bucket = "pg-playground"
bucket_examples_name = "pg-playground-example"
