network_name = "playground"
project_id   = "pg-kuber-test"
gke_name     = "playground-backend"
region       = "us-east1"
pg_location  = "us-east1-b"
state_bucket = "pg-kuber-tst"
bucket_examples_name = "pg-kuber-tst-example"
