# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"

services:
  redis:
    image: redis:7.0.4-alpine
    expose:
      - 6379

  datastore:
    build: "./backend/containers/router/datastore"
    environment:
      DATASTORE_PROJECT_ID: test
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    expose:
      - 8081

  mitmproxy:
    image: apache/beam_playground-backend-mitmproxy
    expose:
      - 8080

  router:
    image: apache/beam_playground-backend-router
    environment:
      GOOGLE_CLOUD_PROJECT: test
      DATASTORE_EMULATOR_HOST: datastore:8081
      CACHE_TYPE: remote
      CACHE_ADDRESS: redis:6379
      SDK_CONFIG: /opt/playground/backend/sdks-emulator.yaml
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - datastore

  go_runner:
    image: apache/beam_playground-backend-go
    environment:
      GOOGLE_CLOUD_PROJECT: test
      CACHE_TYPE: remote
      CACHE_ADDRESS: redis:6379
      SERVER_PORT: 8084
      PLAYGROUND_MITM_SERVICE_HOST: mitmproxy
      PLAYGROUND_MITM_SERVICE_PORT: 8080
    ports:
      - "8084:8084"
    depends_on:
      - redis
      - mitmproxy

  java_runner:
    image: apache/beam_playground-backend-java
    environment:
      GOOGLE_CLOUD_PROJECT: test
      CACHE_TYPE: remote
      CACHE_ADDRESS: redis:6379
      SERVER_PORT: 8086
      PLAYGROUND_MITM_SERVICE_HOST: mitmproxy
      PLAYGROUND_MITM_SERVICE_PORT: 8080
    ports:
      - "8086:8086"
    depends_on:
      - redis
      - mitmproxy

  python_runner:
    image: apache/beam_playground-backend-python
    environment:
      GOOGLE_CLOUD_PROJECT: test
      CACHE_TYPE: remote
      CACHE_ADDRESS: redis:6379
      SERVER_PORT: 8088
      PLAYGROUND_MITM_SERVICE_HOST: mitmproxy
      PLAYGROUND_MITM_SERVICE_PORT: 8080
    ports:
      - "8088:8088"
    depends_on:
      - redis
      - mitmproxy

  scio_runner:
    image: apache/beam_playground-backend-scio
    environment:
      GOOGLE_CLOUD_PROJECT: test
      CACHE_TYPE: remote
      CACHE_ADDRESS: redis:6379
      SERVER_PORT: 8090
      PLAYGROUND_MITM_SERVICE_HOST: mitmproxy
      PLAYGROUND_MITM_SERVICE_PORT: 8080
    ports:
      - "8090:8090"
    depends_on:
      - mitmproxy
      - redis
    # Impose limits on container to better mimic real deployment environment
    mem_limit: 2048M
    ulimits:
      rss: 1073741824

  frontend:
    image: apache/beam_playground-frontend
    ports:
      - "1234:8080"
    depends_on:
      - router
